<a href="https://colab.research.google.com/github/scaballero1018/programacion1/blob/main/entrenamiento_parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sergio andres Caballero Hernandez

In [5]:
import numpy as np

In [6]:
a= np.array(["c","p","m","m","n"])

In [7]:
np.sort(a)

array(['c', 'm', 'm', 'n', 'p'], dtype='<U1')

los ordena alfabeticamente

In [8]:
np.unique(a)

array(['c', 'm', 'n', 'p'], dtype='<U1')

Elimina valores repetido y deja un solo valor porcada elemento

In [9]:
np.concatenate[(a,a)]

TypeError: 'numpy._ArrayFunctionDispatcher' object is not subscriptable

In [11]:
np.reshape(a,(5,1))

array([['c'],
       ['p'],
       ['m'],
       ['m'],
       ['n']], dtype='<U1')

cambia la dimencion del arreglo numpy inicialmente utilizado. este caso el arreglo es de 2 filas y 4 columnas.

In [12]:
import pandas as pd
b_pd = pd.DataFrame(a)
b_pd

   0
0  c
1  p
2  m
3  m
4  n

como volver el archivo en data frame

In [13]:
a[a !="m"]

array(['c', 'p', 'n'], dtype='<U1')

diferentes de m

In [14]:
a[a=="m"]

array(['m', 'm'], dtype='<U1')

igaules a m

In [15]:
a[a>"n"]

array(['p'], dtype='<U1')

a[a>n]

como se hace la suma de matrices en numpy

el producto de adamar [elemento a elemento]

In [31]:
D=np.array([[1,3],[4,5]])
C=np.array([[24,6],[3,9]])
D*C

array([[24, 18],
       [12, 45]])

In [37]:
m=np.array([D,C])
m

array([[[ 1,  3],
        [ 4,  5]],

       [[24,  6],
        [ 3,  9]]])

In [38]:
m*D

array([[[ 1,  9],
        [16, 25]],

       [[24, 18],
        [12, 45]]])

In [34]:
import pandas as pd
df= pd.DataFrame({
    "nombre":["ana","camilo","carlos"],
    "edad": [23,25,27],
    "nota":[4,4.5,5]
})
df

   nombre  edad  nota
0     ana    23   4.0
1  camilo    25   4.5
2  carlos    27   5.0

In [23]:
df["edad"]

0    23
1    25
2    27
Name: edad, dtype: int64

In [24]:
df.iloc[0]

nombre    ana
edad       23
nota      4.0
Name: 0, dtype: object

In [ ]:
df.loc[]

In [25]:
df.loc[df["nombre"]=="carlos"]

   nombre  edad  nota
2  carlos    27   5.0

In [ ]:
df.loc[df['edad']>23]

el promedio de edades

In [ ]:
df.sum()

el metodo sumas concadena cadena
y la edad total de las letras

In [10]:
df.min()

NameError: name 'df' is not defined

la salida es la palabra por el orden alfabetic. y para numeros son los valores minimos

In [ ]:
df.max()

In [ ]:
df.describe()

ver como se describe

In [ ]:
describe

In [ ]:
df[]

punto del parcia es funcio lambda

In [ ]:
df["edad"].apply(lambda x: x+1)

sumarle 1 ala edad

proyectos

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(123)#para guardar la semilla

In [ ]:
datos= np.random.normal(loc=4.0, scale=0.5,size=50)#simula loc= ala media scale=es la desviacion estandar 0.5
df=pd.DataFrame({
    "nota":datos
})

In [ ]:
df.describe()

std es la desvidacion estandar

In [ ]:
media=df["nota"].mean()

In [ ]:
import matplotlib.pyplot as plt

df["nota"].hist()
plt.title("Histogram of Notas")
plt.xlabel("Nota Value")
plt.ylabel("Frequency")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
import numpy as np

# Get the data
notas = df["nota"]

# Create a figure and axes
plt.figure(figsize=(10, 6))

# Plot histogram and KDE using seaborn
sns.histplot(notas, kde=True, stat="density", color="skyblue", label="Histograma y KDE")

# Fit a normal distribution to the data
mu, std = norm.fit(notas)

# Plot the PDF of the fitted normal distribution
x = np.linspace(notas.min(), notas.max(), 100)
p = norm.pdf(x, mu, std)
plt.plot(x, p, 'r--', linewidth=2, label=f'Ajuste Normal ($\mu$={mu:.2f}, $\sigma$={std:.2f})')

# Add titles and labels for a 'bonito' plot
plt.title('Distribución de Notas con KDE y Ajuste Normal', fontsize=16)
plt.xlabel('Valor de Nota', fontsize=12)
plt.ylabel('Densidad', fontsize=12)
plt.legend(fontsize=10)
plt.grid(axis='y', alpha=0.75)
plt.show()

In [ ]:
from scipy.stats import shapiro
shapiro(df["nota"])

como el valor p es mayor que 0.05, no se rechaza la hipotesis de la  normalidad

si fuera menor que 0.05 se rechaza la hipotesis de normalidad

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(123)

grupo_A = np.random.normal(loc=4.0, scale=0.4, size=40)
grupo_B = np.random.normal(loc=4.3, scale=0.5, size=40)

df = pd.DataFrame({
    "A": grupo_A,
    "B": grupo_B
})

In [ ]:
from scipy import stats
t_stat, p_val = stats.ttest_ind(df["A"], df["B"])

print("Estadístico t:", t_stat)
print("Valor p:", p_val)

como los valores de p son menores de 0.05 se rechaza la hipotesis de la normal con una confianza del 95%